name: Sync to GitCode
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Sync to GitCode
      run: |
        git remote add gitcode https://gitcode.net/${{ secrets.GITCODE_USERNAME }}/${{ secrets.GITCODE_REPO_NAME }}.git
        git push gitcode master
      env:
        GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}