name: Sync to GitCode
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config --global user.name "ceshi"
        git config --global user.email "ceshi@gmail.com"
    - name: Test network connection
      run: |
        curl -I https://gitcode.com
    - name: Sync to GitCode
      run: |
        git remote add gitcode https://$GITCODE_USERNAME:$GITCODE_TOKEN@gitcode.com/$GITCODE_USERNAME/$GITCODE_REPO_NAME.git
        git push gitcode master --force
      env:
        GITCODE_USERNAME: ${{ secrets.GITCODE_USERNAME }}
        GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        GITCODE_REPO_NAME: ${{ secrets.GITCODE_REPO_NAME }}